import { Container } from 'inversify';
import { ILoggerService } from './logger/ilogger';
import { LoggerService } from './logger/logger.service';
import { TYPES } from './types';
import { UserController } from './user/user.controller';
import { IExeptionFilter } from './common/error/exeption.filter.interface';
import { ExeptionFilter } from './common/error/exeption.filter';
import { App } from './app';
import { MongooseServise } from './database/mongoose.servise';
import { UserRepository } from './user/user.repository';
import { UserService } from './user/user.service';
import { IUserController } from './user/user-interfaces/user.icontroller';
import { IUserRepository } from './user/user-interfaces/user.irepository';
import { IUserService } from './user/user-interfaces/user.iservice';
import { IConfigService } from './config/Iconfig-service';
import { ConfigService } from './config/config.service';
import { ITextRepository } from './text/text-interfaces/text.irepository';
import { TextRepository } from './text/text.repository';
import { ITextService } from './text/text-interfaces/text.iservice';
import { TextService } from './text/text.service';
import { ITextController } from './text/text-interfaces/text.icontroller';
import { TextController } from './text/text.controller';

const appContainer = new Container();
appContainer.bind<ILoggerService>(TYPES.LoggerService).to(LoggerService).inSingletonScope();
appContainer.bind<IUserController>(TYPES.UserController).to(UserController);
appContainer.bind<ITextController>(TYPES.TextController).to(TextController);
appContainer.bind<IExeptionFilter>(TYPES.ExeptionFilterService).to(ExeptionFilter);
appContainer.bind<MongooseServise>(TYPES.MongooseServise).to(MongooseServise).inSingletonScope();
appContainer.bind<IUserRepository>(TYPES.UserRepository).to(UserRepository).inSingletonScope();
appContainer.bind<ITextRepository>(TYPES.TextRepository).to(TextRepository).inSingletonScope();
appContainer.bind<IUserService>(TYPES.UserService).to(UserService).inSingletonScope();
appContainer.bind<ITextService>(TYPES.TextService).to(TextService).inSingletonScope();
appContainer.bind<IConfigService>(TYPES.ConfigService).to(ConfigService).inSingletonScope();
appContainer.bind<App>(TYPES.Application).to(App);

const app = appContainer.get<App>(TYPES.Application);
app.init();

export { app, appContainer };
